create table app_user (
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    name varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
 );

create table driver (
    available boolean,
    rating float(53),
    id bigint generated by default as identity,
    user_id bigint unique,
    vehicle_id bigint unique,
    current_location Geometry(Point, 4326),
    primary key (id)
);

create table payment (
    amount numeric(38,2),
    id bigint generated by default as identity,
    payment_time timestamp(6),
    ride_id bigint unique,
    payment_method varchar(255) check (payment_method in ('CASH','WALLET')),
    payment_status varchar(255) check (payment_status in ('PENDING','CONFIRMED','REFUNDED')),
    primary key (id)
);

create table rating (
    driver_rating integer,
    rider_rating integer,
    driver_id bigint,
    id bigint generated by default as identity,
    ride_id bigint unique,
    rider_id bigint,
    primary key (id)
);

create table ride (
    fare numeric(38,2),
    created_time timestamp(6),
    driver_id bigint,
    ended_at timestamp(6),
    id bigint generated by default as identity,
    rider_id bigint,
    started_at timestamp(6),
    otp varchar(255),
    payment_method varchar(255) check (payment_method in ('CASH','WALLET')),
    ride_status varchar(255) check (ride_status in ('CANCELLED','CONFIRMED','ENDED','ONGOING')),
    drop_location Geometry(Point, 4326),
    pickup_location Geometry(Point, 4326),
    primary key (id)
);

create table rider (
    rating float(53),
    id bigint generated by default as identity,
    user_id bigint unique,
    primary key (id)
);

create table ride_request (
    fare numeric(38,2),
    id bigint generated by default as identity,
    requested_time timestamp(6),
    rider_id bigint,
    payment_method varchar(255) check (payment_method in ('CASH','WALLET')),
    ride_request_status varchar(255) check (ride_request_status in ('PENDING','CANCELLED','CONFIRMED')),
    drop_location Geometry(Point, 4326),
    pickup_location Geometry(Point, 4326),
    primary key (id)
);

create table session (
    id bigint generated by default as identity,
    last_used_at timestamp(6),
    user_id bigint,
    refresh_token varchar(255),
    primary key (id)
);

create table user_roles (
    user_id bigint not null,
    roles varchar(255) check (roles in ('ADMIN','DRIVER','RIDER'))
);

create table vehicle (
    id bigint generated by default as identity,
    name varchar(255),
    vehicle_type varchar(255) check (vehicle_type in ('SEDAN','HATCHBACK','SUV')),
    primary key (id)
);

create table wallet (
    balance numeric(38,2),
    id bigint generated by default as identity,
    user_id bigint not null unique,
    primary key (id)
);

create table wallet_transaction (
    amount numeric(38,2),
    id bigint generated by default as identity,
    ride_id bigint,
    timestamp timestamp(6),
    wallet_id bigint,
    transaction_id varchar(255),
    transaction_method varchar(255) check (transaction_method in ('BANKING','RIDE')),
    transaction_type varchar(255) check (transaction_type in ('CREDIT','DEBIT')),
    primary key (id)
);

create index idx_rating_rider
   on rating (rider_id);

create index idx_rating_driver
   on rating (driver_id);

create index idx_rider
   on ride (rider_id);

create index idx_driver
   on ride (driver_id);

create index idx_ride_request_rider
   on ride_request (rider_id);

create index idx_wallet_transaction_wallet
   on wallet_transaction (wallet_id, ride_id);

alter table if exists driver
   add constraint FK29a5l15muu6jqd77k1vp91fhw
   foreign key (user_id)
   references app_user;

alter table if exists driver
   add constraint FKjvtsi9cks0ah62ffq4ilpi8oj
   foreign key (vehicle_id)
   references vehicle;

alter table if exists payment
   add constraint FKtlyjkef4sm6h6g777mxgoh81v
   foreign key (ride_id)
   references ride;

alter table if exists rating
   add constraint FKj9037d2patnmrrx9qicig3kah
   foreign key (driver_id)
   references driver;

alter table if exists rating
   add constraint FKii3wln61740uwnqfurghfwly5
   foreign key (ride_id)
   references ride;

alter table if exists rating
   add constraint FKbce6twlxiyai3w14oj8nrm02k
   foreign key (rider_id)
   references rider;

alter table if exists ride
   add constraint FKo12dq19jo25foqggvedgvaa0p
   foreign key (driver_id)
   references driver;

alter table if exists ride
   add constraint FKojie7hvuyn0t49px5hsxt5cr8
   foreign key (rider_id)
   references rider;

alter table if exists rider
   add constraint FKpciwlqisj1l3dbqsv52bg76kd
   foreign key (user_id)
   references app_user;

alter table if exists ride_request
   add constraint FKcduxgbjabdg5yolikiws9vn7p
   foreign key (rider_id)
   references rider;

alter table if exists session
   add constraint FK3ytt9yah3j54hpllng184c6kf
   foreign key (user_id)
   references app_user;

alter table if exists user_roles
   add constraint FK6fql8djp64yp4q9b3qeyhr82b
   foreign key (user_id)
   references app_user;

alter table if exists wallet
   add constraint FK8xcge928o78vtbh64bddusygy
   foreign key (user_id)
   references app_user;

alter table if exists wallet_transaction
   add constraint FK4ayshp0r354bi0ulfxpmdfdvm
   foreign key (ride_id)
   references ride;

alter table if exists wallet_transaction
   add constraint FK6cnvafp3a0xhbs0eh9w26sett
   foreign key (wallet_id)
   references wallet;